import Header from "./account/_components/Header";

import "@/app/_styles/globals.css";
import SideNavigation from "./account/_components/SideNavigation";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-slate-300 text-gray-900 min-h-screen flex flex-col">
        <Header />
        <div className="grid grid-cols-[16rem_1fr] gap-12 h-full flex-1">
          <SideNavigation />
          <main className="py-1 bg-red-300">{children}</main>
        </div>
      </body>
    </html>
  );
}
